use_frameworks!

platform :ios, '9.0'

target 'TRUNetwork_Example' do
  pod 'TRUNetwork', :path => '../'

  target 'TRUNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
